In [30]:
import scipy.io
import pandas as pd
import numpy as np

In [31]:
df1 = pd.read_csv("OysterMetro_Complete_Sample_Feature_Extracted_new.csv").round(6)
df2 = pd.read_csv("OysterMetro_n12617.csv").round(6)

# Initialize an empty list to store the matching indices
matching_indices_df2 = []
print("start")
# Iterate over each row in df1
for i, row in df1.iterrows():
    # Find the index in df2 that matches the current row in df1
    try:
        matching_index = df2[(df2['EntTime'] == row['EntTime']) &  (df2['OriginLongitude'] == row['OriginLongitude']) & (df2['OriginLatitude'] == row['OriginLatitude']) & (df2['DestinationLongitude'] == row['DestinationLongitude']) & (df2['DestinationLatitude'] == row['DestinationLatitude']) & (df2['downo_sin'] == row['downo_sin']) & (df2['downo_cos'] == row['downo_cos'])].index[0]
    # Append the found index to the list
        df2.xs(matching_index)['TotalDistance']=row['TotalDistance']
    except:
        continue

start


In [32]:
pd.read_csv("OysterMetro_n12617.csv")

EntTime    ExTime  OriginLongitude  OriginLatitude  \
0      0.317582  0.322495         0.538338        0.652926   
1      0.944406  0.908427         0.547831        0.535297   
2      0.664350  0.641672         0.553663        0.468290   
3      0.339124  0.336430         0.686071        0.451660   
4      0.726199  0.702721         0.560003        0.472610   
...         ...       ...              ...             ...   
12612  0.708826  0.691440         0.686071        0.451660   
12613  0.735928  0.728600         0.813291        0.647465   
12614  0.325226  0.339748         0.704284        0.555214   
12615  0.733148  0.706702         0.599459        0.474784   
12616  0.473245  0.470471         0.802315        0.549318   

       DestinationLongitude  DestinationLatitude  TotalTime  TotalDistance  \
0                  0.619738             0.470165   0.316239       0.198912   
1                  0.585919             0.617575   0.153846       0.090609   
2                  0.496594             0.504701   0.162393       0.083066   
3                  0.548372             0.508722   0.230769       0.190951   
4                  0.571455             0.572061   0.188034       0.091983   
...                     ...                  ...        ...            ...   
12612              0.613307             0.489756   0.256410       0.103121   
12613              0.553470             0.440873   0.401709       0.394403   
12614              0.511241             0.345117   0.444444       0.321075   
12615              0.543504             0.460301   0.153846       0.075824   
12616              0.524852             0.479865   0.307692       0.375476   

       downo_sin     downo_cos  
0       0.099031  8.019377e-01  
1       1.000000  3.568959e-01  
2       0.000000  3.568959e-01  
3       0.000000  3.568959e-01  
4       0.099031  8.019377e-01  
...          ...           ...  
12612   0.099031  8.019377e-01  
12613   0.000000  3.568959e-01  
12614   0.000000  3.568959e-01  
12615   0.722521  5.551115e-17  
12616   0.500000  1.000000e+00  

[12617 rows x 10 columns]

In [33]:
df2

EntTime    ExTime  OriginLongitude  OriginLatitude  \
0      0.317582  0.322495         0.538338        0.652926   
1      0.944406  0.908427         0.547831        0.535297   
2      0.664350  0.641672         0.553663        0.468290   
3      0.339124  0.336430         0.686071        0.451660   
4      0.726199  0.702721         0.560003        0.472610   
...         ...       ...              ...             ...   
12612  0.708826  0.691440         0.686071        0.451660   
12613  0.735928  0.728600         0.813291        0.647465   
12614  0.325226  0.339748         0.704284        0.555214   
12615  0.733148  0.706702         0.599459        0.474784   
12616  0.473245  0.470471         0.802315        0.549318   

       DestinationLongitude  DestinationLatitude  TotalTime  TotalDistance  \
0                  0.619738             0.470165   0.316239       0.203040   
1                  0.585919             0.617575   0.153846       0.116604   
2                  0.496594             0.504701   0.162393       0.089317   
3                  0.548372             0.508722   0.230769       0.169652   
4                  0.571455             0.572061   0.188034       0.075081   
...                     ...                  ...        ...            ...   
12612              0.613307             0.489756   0.256410       0.114061   
12613              0.553470             0.440873   0.401709       0.356973   
12614              0.511241             0.345117   0.444444       0.291720   
12615              0.543504             0.460301   0.153846       0.058641   
12616              0.524852             0.479865   0.307692       0.305746   

       downo_sin  downo_cos  
0       0.099031   0.801938  
1       1.000000   0.356896  
2       0.000000   0.356896  
3       0.000000   0.356896  
4       0.099031   0.801938  
...          ...        ...  
12612   0.099031   0.801938  
12613   0.000000   0.356896  
12614   0.000000   0.356896  
12615   0.722521   0.000000  
12616   0.500000   1.000000  

[12617 rows x 10 columns]

In [34]:
df3 = df2.round(6)

# Load the MATLAB file
mat_train = scipy.io.loadmat('traindata.mat')
mat_train_X = mat_train['X']

# Convert the MATLAB matrix to a DataFrame
df4 = pd.DataFrame(mat_train_X).round(6)
df4.columns=df3.columns

# Initialize an empty list to store the matching indices
matching_indices_df4 = []

# Iterate over each row in df1
for i, row in df3.iterrows():
    # Find the index in df4 that matches the current row in df3
    try:
        matching_index = df4[(df4['EntTime'] == row['EntTime']) & (df4['ExTime'] == row['ExTime']) & (df4['OriginLongitude'] == row['OriginLongitude']) & (df4['OriginLatitude'] == row['OriginLatitude']) & (df4['DestinationLongitude'] == row['DestinationLongitude']) & (df4['DestinationLatitude'] == row['DestinationLatitude']) & (df4['TotalTime'] == row['TotalTime']) & (df4['downo_sin'] == row['downo_sin']) & (df4['downo_cos'] == row['downo_cos'])].index[0]
    # Append the found index to the list
        df4.xs(matching_index)['TotalDistance']=row['TotalDistance']
    except:
        continue

In [35]:
df4

EntTime    ExTime  OriginLongitude  OriginLatitude  \
0      0.525365  0.518912         0.624645        0.668442   
1      0.747047  0.717983         0.608954        0.454633   
2      0.534399  0.520239         0.318055        0.657654   
3      0.851286  0.828135         0.543504        0.460301   
4      0.746352  0.719973         0.608954        0.454622   
...         ...       ...              ...             ...   
10088  0.436414  0.426676         0.547831        0.535297   
10089  0.728978  0.715328         0.565068        0.524292   
10090  0.820709  0.803583         0.543504        0.460301   
10091  0.775539  0.759124         0.358610        0.482311   
10092  0.663655  0.635700         0.483600        0.854111   

       DestinationLongitude  DestinationLatitude  TotalTime  TotalDistance  \
0                  0.524852             0.479865   0.290598       0.182024   
1                  0.624026             0.482914   0.128205       0.039828   
2                  0.155683             0.568176   0.196581       0.189481   
3                  0.484694             0.716102   0.264957       0.214564   
4                  0.541831             0.432205   0.162393       0.070166   
...                     ...                  ...        ...            ...   
10088              0.517698             0.679229   0.196581       0.115248   
10089              0.513131             0.243710   0.316239       0.254732   
10090              0.564714             0.732759   0.324786       0.226259   
10091              0.595550             0.482229   0.307692       0.271171   
10092              0.493728             0.762214   0.094017       0.067115   

       downo_sin  downo_cos  
0       0.900969   0.801938  
1       0.722521   0.000000  
2       0.099031   0.801938  
3       0.000000   0.356896  
4       1.000000   0.356896  
...          ...        ...  
10088   0.000000   0.356896  
10089   0.099031   0.801938  
10090   1.000000   0.356896  
10091   0.000000   0.356896  
10092   1.000000   0.356896  

[10093 rows x 10 columns]

In [36]:
pd.DataFrame(mat_train['X'])

0         1         2         3         4         5         6  \
0      0.525365  0.518912  0.624645  0.668442  0.524852  0.479865  0.290598   
1      0.747047  0.717983  0.608954  0.454633  0.624026  0.482914  0.128205   
2      0.534399  0.520239  0.318055  0.657654  0.155683  0.568176  0.196581   
3      0.851286  0.828135  0.543504  0.460301  0.484694  0.716102  0.264957   
4      0.746352  0.719973  0.608954  0.454622  0.541831  0.432205  0.162393   
...         ...       ...       ...       ...       ...       ...       ...   
10088  0.436414  0.426676  0.547831  0.535297  0.517698  0.679229  0.196581   
10089  0.728978  0.715328  0.565068  0.524292  0.513131  0.243710  0.316239   
10090  0.820709  0.803583  0.543504  0.460301  0.564714  0.732759  0.324786   
10091  0.775539  0.759124  0.358610  0.482311  0.595550  0.482229  0.307692   
10092  0.663655  0.635700  0.483600  0.854111  0.493728  0.762214  0.094017   

              7         8             9  
0      0.217447  0.900969  8.019377e-01  
1      0.032708  0.722521  5.551115e-17  
2      0.231286  0.099031  8.019377e-01  
3      0.246129  0.000000  3.568959e-01  
4      0.091886  1.000000  3.568959e-01  
...         ...       ...           ...  
10088  0.137284  0.000000  3.568959e-01  
10089  0.265139  0.099031  8.019377e-01  
10090  0.250105  1.000000  3.568959e-01  
10091  0.316125  0.000000  3.568959e-01  
10092  0.084895  1.000000  3.568959e-01  

[10093 rows x 10 columns]

In [37]:
mat_train['X']=np.array(df4)
mat_train['X'][0]

array([0.525365, 0.518912, 0.624645, 0.668442, 0.524852, 0.479865,
       0.290598, 0.182024, 0.900969, 0.801938])

In [38]:
scipy.io.loadmat('traindata.mat')['X'][0]

array([0.52536484, 0.51891175, 0.62464492, 0.66844193, 0.52485249,
       0.47986522, 0.29059829, 0.21744737, 0.90096887, 0.80193774])

In [39]:
from scipy.io import savemat
savemat("new_traindata.mat", mat_train)

In [40]:
df3 = df2.round(6)

# Load the MATLAB file
mat_test = scipy.io.loadmat('testdata.mat')
mat_test_X = mat_test['X']

# Convert the MATLAB matrix to a DataFrame
df4 = pd.DataFrame(mat_test_X).round(6)
df4.columns=df3.columns

# Initialize an empty list to store the matching indices
matching_indices_df4 = []

# Iterate over each row in df1
for i, row in df3.iterrows():
    # Find the index in df4 that matches the current row in df3
    try:
        matching_index = df4[(df4['EntTime'] == row['EntTime']) & (df4['ExTime'] == row['ExTime']) & (df4['OriginLongitude'] == row['OriginLongitude']) & (df4['OriginLatitude'] == row['OriginLatitude']) & (df4['DestinationLongitude'] == row['DestinationLongitude']) & (df4['DestinationLatitude'] == row['DestinationLatitude']) & (df4['TotalTime'] == row['TotalTime']) & (df4['downo_sin'] == row['downo_sin']) & (df4['downo_cos'] == row['downo_cos'])].index[0]
    # Append the found index to the list
        df4.xs(matching_index)['TotalDistance']=row['TotalDistance']
    except:
        continue

In [41]:
df4

EntTime    ExTime  OriginLongitude  OriginLatitude  \
0     0.412092  0.428666         0.445081        0.457910   
1     0.440584  0.426012         0.465018        0.488696   
2     0.699097  0.693431         0.569740        0.488778   
3     0.364837  0.376908         0.762772        0.785881   
4     0.731758  0.706702         0.565068        0.524292   
...        ...       ...              ...             ...   
2519  0.732453  0.728600         0.527265        0.421173   
2520  0.437109  0.427339         0.575869        0.340688   
2521  0.874218  0.851360         0.566812        0.461796   
2522  0.268937  0.271400         0.576957        0.000000   
2523  0.354413  0.356337         0.817702        0.721401   

      DestinationLongitude  DestinationLatitude  TotalTime  TotalDistance  \
0                 0.686071             0.451660   0.521368       0.292232   
1                 0.445081             0.457910   0.136752       0.040424   
2                 0.296877             0.370496   0.401709       0.337947   
3                 0.541831             0.432205   0.435897       0.385741   
4                 0.538338             0.652926   0.170940       0.224903   
...                    ...                  ...        ...            ...   
2519              0.300796             0.617684   0.444444       0.323880   
2520              0.524852             0.479865   0.196581       0.139484   
2521              0.729240             0.526955   0.282051       0.182532   
2522              0.541831             0.432205   0.256410       0.359267   
2523              0.613307             0.489756   0.299145       0.338625   

      downo_sin  downo_cos  
0      0.099031   0.801938  
1      1.000000   0.356896  
2      0.099031   0.801938  
3      0.722521   0.000000  
4      0.099031   0.801938  
...         ...        ...  
2519   0.722521   0.000000  
2520   0.277479   0.000000  
2521   1.000000   0.356896  
2522   0.099031   0.801938  
2523   0.277479   0.000000  

[2524 rows x 10 columns]

In [42]:
pd.DataFrame(mat_test['X'])

0         1         2         3         4         5         6  \
0     0.412092  0.428666  0.445081  0.457910  0.686071  0.451660  0.521368   
1     0.440584  0.426012  0.465018  0.488696  0.445081  0.457910  0.136752   
2     0.699097  0.693431  0.569740  0.488778  0.296877  0.370496  0.401709   
3     0.364837  0.376908  0.762772  0.785881  0.541831  0.432205  0.435897   
4     0.731758  0.706702  0.565068  0.524292  0.538338  0.652926  0.170940   
...        ...       ...       ...       ...       ...       ...       ...   
2519  0.732453  0.728600  0.527265  0.421173  0.300796  0.617684  0.444444   
2520  0.437109  0.427339  0.575869  0.340688  0.524852  0.479865  0.196581   
2521  0.874218  0.851360  0.566812  0.461796  0.729240  0.526955  0.282051   
2522  0.268937  0.271400  0.576957  0.000000  0.541831  0.432205  0.256410   
2523  0.354413  0.356337  0.817702  0.721401  0.613307  0.489756  0.299145   

             7         8             9  
0     0.321650  0.099031  8.019377e-01  
1     0.038679  1.000000  3.568959e-01  
2     0.379849  0.099031  8.019377e-01  
3     0.436777  0.722521  5.551115e-17  
4     0.122615  0.099031  8.019377e-01  
...        ...       ...           ...  
2519  0.351237  0.722521  5.551115e-17  
2520  0.144055  0.277479  0.000000e+00  
2521  0.224693  1.000000  3.568959e-01  
2522  0.396981  0.099031  8.019377e-01  
2523  0.344758  0.277479  0.000000e+00  

[2524 rows x 10 columns]

In [43]:
mat_test['X']=np.array(df4)
mat_test['X'][0]

array([0.412092, 0.428666, 0.445081, 0.45791 , 0.686071, 0.45166 ,
       0.521368, 0.292232, 0.099031, 0.801938])

In [44]:
scipy.io.loadmat('testdata.mat')['X'][0]

array([0.41209173, 0.42866622, 0.44508137, 0.4579099 , 0.68607062,
       0.45166024, 0.52136752, 0.3216498 , 0.09903113, 0.80193774])

In [45]:
from scipy.io import savemat
savemat("new_testdata.mat", mat_test)